In [63]:
import numpy as np 
a=np.array([1,2,3])
print(a)

[1 2 3]


In [64]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
#creating a linearly spaced,with spacing
import numpy as np
a=np.linspace(0 , 20 , 5)
print(a)


[ 0.  5. 10. 15. 20.]


In [66]:
import numpy as np
vector=np.linspace(0,20,5)
print(vector)

[ 0.  5. 10. 15. 20.]


In [67]:
import numpy as np
myarr=np.array([1,2,3])
print(myarr)

[1 2 3]


In [68]:
# 1D array 
import numpy as np
np.array([10,20,30])


array([10, 20, 30])

In [69]:
#now i am craete a 2D array
import numpy as np
np.array([[10,20,30],[40,50,60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [70]:
import numpy as np
np.array([[10,20,30,],[40,50,60],[70,80,90]])

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
list1=[[10,20,30],[40,50,60],[70,80,90]]
print(list1)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [72]:
np.array(list1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
np.array([[10,20,30],[40,50,60],[70,80,90]])

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [74]:
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(type(b))

<class 'numpy.ndarray'>


In [75]:
np.array([[10,20,30],[40,60]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
np.array([[10,20,30],[40,0,60]])

In [ ]:
import numpy as np
np.array([[10,20,30],[40,np.nan,60]])


In [ ]:
import numpy as np
a=[[10,20,30],[40,np.nan,60],[70,np.nan,np.nan]]
myarr=np.array(a)
print(myarr)

In [ ]:
import numpy as np
np.array([[10,20,30],[40,'sat',"50"]])


In [ ]:
list1=[[10,20,30],[40,'sat',90]]
print(list1)

In [ ]:
np.array(list1)

In [ ]:
#if we have boolean value True ,False the check it
list1=[[10,20,30],[40,True,60]]
print(list1)

In [ ]:
np.array(list1)

In [ ]:
list1=[[10,20,30],[40,False,60]]
print(list1)

In [ ]:
np.array(list1)

In [ ]:
a=np.array([[10,20,30],[50,60,70]])
print(a)

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a=[[10,20,30],[40,50,60],[70,80,90]]
print(a)


In [ ]:
b=np.array(a)

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
display(b)

In [ ]:
b=np.array([[10,20,30],[50,60,70],[80,90,99]])
print(b)

In [ ]:

print(type(b))

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
import numpy as np
list1=([[10,20,30,40],[50,60,70,80]])
print(list1)
a=np.array([[10,20,30,40],[50,60,70,80]])
print(a)
print(type(a))

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
np.arange(5)

In [ ]:
np.arange(10,20)

In [ ]:
np.arange(10)

In [ ]:
np.arange(10,20)

In [ ]:
np.arange(1,10,2)

In [ ]:
np.arange(9)

In [ ]:
np.arange(100,10,-10)

In [ ]:
import numpy as np
a=([[10,20,30],[40,50,60],[70,80,90]])
myarr=np.array(a)
print(myarr)

In [ ]:
import numpy as np
np.array([1,2,3])

In [ ]:
import numpy as np
np.array([[1,2,3],[4,5,6],[7,8,9]])


In [76]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [77]:
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
print(type(list1))

<class 'list'>


In [79]:
import numpy as np
a=[[10,20,30],[40,50,60],[80,90,70]]
myarr=np.array(a)
print(myarr)

[[10 20 30]
 [40 50 60]
 [80 90 70]]


In [80]:
print(type(myarr))

<class 'numpy.ndarray'>


In [81]:
list2=[[10,20,30],[50,0,70],[90,0,90]]
print(list2)

[[10, 20, 30], [50, 0, 70], [90, 0, 90]]


In [ ]:
np.array(list2)

In [ ]:
np.array([[10,20,30],[50,np.nan,70],[90,np.nan,90]])


In [ ]:
list=[[10,20,30],[80,True,90]]
list

In [ ]:
np.array(list)


In [ ]:
list=[[10,20,30],[80,False,90]]
list

In [ ]:
np.array(list)

In [ ]:
a=np.array([[10,20,30],[50,60,70],[90,80,70]])
print(a)

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
display(a)

In [ ]:
b=np.array([[10,20,30],[60,30,50,],[90,80,70]])
print(b)

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
display(b)

In [ ]:
np.arange(5)

In [ ]:
np.arange(8)

In [ ]:
np.arange(1,20,2)

In [ ]:
np.arange(100,10,-10)

In [ ]:
np.arange(1,10,0.5)

In [94]:
b=np.arange(9)
print(b)

[0 1 2 3 4 5 6 7 8]


In [93]:
display(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
b.reshape(3,3)

ValueError: cannot reshape array of size 30 into shape (3,3)

In [91]:
b=np.arange(30)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [90]:
display(b)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
b.reshape(6,5)

ValueError: cannot reshape array of size 25 into shape (6,5)

In [88]:
b.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [87]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
#3D array
b.reshape(2,5,3)

ValueError: cannot reshape array of size 25 into shape (2,5,3)

In [85]:
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
a*5

[[10, 20, 30],
 [40, 50, 60],
 [80, 90, 70],
 [10, 20, 30],
 [40, 50, 60],
 [80, 90, 70],
 [10, 20, 30],
 [40, 50, 60],
 [80, 90, 70],
 [10, 20, 30],
 [40, 50, 60],
 [80, 90, 70],
 [10, 20, 30],
 [40, 50, 60],
 [80, 90, 70]]

In [83]:
type

type

In [96]:
import numpy as np
b=np.array([1,2,3])
b


array([1, 2, 3])

In [97]:
type(b)

numpy.ndarray

In [98]:
import numpy as pajju
pajju.array([1,2,3])

array([1, 2, 3])

In [100]:
import numpy as pajju
m=pajju.array([[1,2,3],[4,5,6],[6,7,8]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [101]:
display(m)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [102]:
pajju.arange(5)

array([0, 1, 2, 3, 4])

In [103]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [106]:
b=pajju.arange(30)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [107]:
b.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [109]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [113]:
m=np.array(list1)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
display(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
n=np.arange(9)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
n.ndim

1

In [123]:
n=np.arange(9)
print(n)

[0 1 2 3 4 5 6 7 8]


In [127]:
p=np.arange(30)
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [128]:
p.reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [129]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [133]:
b=np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
b*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [136]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.array([[1,2,3],[4,5,0]])

array([[1, 2, 3],
       [4, 5, 0]])

In [141]:
np.array([[1,2,3],[4,5,np.nan]])

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [143]:
import numpy as np
np.array([[1,2,3],[4,5,6],[8,9,8]])


array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 8]])

In [150]:
import numpy as np
a=[[1,2,3],[6,7,8],[7,9,8]]
myarr=np.array(a)
print(myarr)

[[1 2 3]
 [6 7 8]
 [7 9 8]]


In [4]:
import numpy as np
c=np.arange(30,60,1)
print(c)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]


In [7]:
# it is a 1D array
d=np.arange(30,60,1)
d

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
d.reshape(6,5)

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [11]:
d.reshape(3,10)

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [12]:
d.reshape(10,3)

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [14]:
d.reshape(2,3,5)

array([[[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [15]:
d.reshape(2,5,3)

array([[[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
p=np.ones((3,3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
type(p)

numpy.ndarray

In [21]:
p*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [23]:
mat1=np.arange(0,30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
mat1=np.arange(0,30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
mat2=np.reshape(mat1,(6,5),"F")
print(mat1)
mat2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [36]:
mat1=np.arange(0,30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
mat2=np.reshape(mat1,(6,5),"C")
print(mat1)
(mat2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [3]:
import numpy as np
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a=np.arange(0,30)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
b=np.reshape(a,(6,5),'F')
print(b)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [16]:
b=np.reshape(a,(5,6),"C")
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
b=np.reshape(a,(5,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
pajju1=np.arange(0,30)
pajju1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
pajju2=np.reshape(pajju1,(6,5),"c")
pajju2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
pajju2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [38]:
#tarnspose of the matrix/ rowes and coloumn can be intechanged
pajju2.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [52]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
c=b.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
c.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [57]:
list1=[10,20,30]
list2=[40,50,60]
list3=[70,80,90]
mat1=np.array([list1,list2,list3])
mat1



array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
mat1.T

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [62]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
a=np.arange(2,11,1)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
c=a.reshape(3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [70]:
print(b)
print()
print(c)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [71]:
print(b+c)

[[ 4  6  8]
 [10 12 14]
 [16 18 20]]


In [72]:
print(b-c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [73]:
print(c-b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [75]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
a=np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
c=a.reshape(3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [80]:
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [82]:
print(b+c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [83]:
print(b-c)

[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]


In [84]:
print(c-b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [85]:
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [86]:
print(b*c)

[[ 0  3  8]
 [15 24 35]
 [48 63 80]]


In [6]:
import numpy as np
a=np.arange(9)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a=np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
c=a.reshape(3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
print(b+c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
print(b-c)

[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]


In [13]:
print(c-b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [3]:
import numpy as np
a=np.arange(9)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
a=np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
c=a.reshape(3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
b*c

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [10]:
b/c

array([[0.        , 0.33333333, 0.5       ],
       [0.6       , 0.66666667, 0.71428571],
       [0.75      , 0.77777778, 0.8       ]])

In [11]:
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
b%c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
c%b

C:\Users\HP\AppData\Local\Temp\ipykernel_14100\1784681195.py:1: RuntimeWarning: divide by zero encountered in remainder
  c%b


array([[0, 0, 0],
       [2, 2, 2],
       [2, 2, 2]])

In [14]:
c//b

C:\Users\HP\AppData\Local\Temp\ipykernel_14100\3639078968.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  c//b


array([[0, 3, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
c**b

array([[        1,         3,        16],
       [      125,      1296,     16807],
       [   262144,   4782969, 100000000]])

In [17]:
6*6*6*6

1296

In [18]:
#linspace (creating a  linearly spaced vectore,with spacing)
import numpy as np
mat1=np.linspace(1,30,11)
print(mat1)

[ 1.   3.9  6.8  9.7 12.6 15.5 18.4 21.3 24.2 27.1 30. ]


In [19]:
vector=np.linspace(20,40,6)
vector


array([20., 24., 28., 32., 36., 40.])

In [22]:
pajju=np.linspace(1,10,9)
pajju

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [24]:
type(pajju[1])

numpy.float64

In [25]:
vector=np.linspace(0,90,88)
vector

array([ 0.        ,  1.03448276,  2.06896552,  3.10344828,  4.13793103,
        5.17241379,  6.20689655,  7.24137931,  8.27586207,  9.31034483,
       10.34482759, 11.37931034, 12.4137931 , 13.44827586, 14.48275862,
       15.51724138, 16.55172414, 17.5862069 , 18.62068966, 19.65517241,
       20.68965517, 21.72413793, 22.75862069, 23.79310345, 24.82758621,
       25.86206897, 26.89655172, 27.93103448, 28.96551724, 30.        ,
       31.03448276, 32.06896552, 33.10344828, 34.13793103, 35.17241379,
       36.20689655, 37.24137931, 38.27586207, 39.31034483, 40.34482759,
       41.37931034, 42.4137931 , 43.44827586, 44.48275862, 45.51724138,
       46.55172414, 47.5862069 , 48.62068966, 49.65517241, 50.68965517,
       51.72413793, 52.75862069, 53.79310345, 54.82758621, 55.86206897,
       56.89655172, 57.93103448, 58.96551724, 60.        , 61.03448276,
       62.06896552, 63.10344828, 64.13793103, 65.17241379, 66.20689655,
       67.24137931, 68.27586207, 69.31034483, 70.34482759, 71.37

In [26]:
vector.astype(int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 90])

In [27]:
EU_Sales=[1002,4523,4123,3584]
APAC_Sales=[7854,9654,4582,8583]
US_Sales=[7845,4512,3652,7452]
Sales=np.array([EU_Sales,APAC_Sales,US_Sales])
print(Sales)

[[1002 4523 4123 3584]
 [7854 9654 4582 8583]
 [7845 4512 3652 7452]]


In [28]:
EU_Sales=[1002,4523,4123,3584]
APAC_Sales=[7854,9654,4582,8583]
US_Sales=[7845,4512,3652,7452]
Sales=np.array([EU_Sales,APAC_Sales,US_Sales])
print(Sales)

[[1002 4523 4123 3584]
 [7854 9654 4582 8583]
 [7845 4512 3652 7452]]


: 

In [1]:
#slicing...

import numpy as np
array1=np.arange(100)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [2]:
print(array1[:10])

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(array1[20:])

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [4]:
print(array1[::10])

[ 0 10 20 30 40 50 60 70 80 90]


In [5]:
print(array1[10:50:5])

[10 15 20 25 30 35 40 45]


In [6]:
print(array1[99::-1])

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


In [8]:
print(array1[99::-5])

[99 94 89 84 79 74 69 64 59 54 49 44 39 34 29 24 19 14  9  4]


In [2]:
# Slicig
import numpy as np
arra1=np.arange(100)
print(arra1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
arr_slice=slice(10,20,2)
print(arr_slice)
print(arra1[arr_slice])

slice(10, 20, 2)
[10 12 14 16 18]


In [5]:
arr_slice=slice(20,100,2)
print(arr_slice)
print(arra1[arr_slice])

slice(20, 100, 2)
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [6]:
print(arra1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [7]:
print(arra1[10::10])

[10 20 30 40 50 60 70 80 90]


In [2]:
#Extracting perticuler rowes and columns using Slicing

import numpy as np
arr1=np.arange(9)
print(arr1)

[0 1 2 3 4 5 6 7 8]


In [3]:
arr2=arr1.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
print(arr2[1:3,1:3])

[[4 5]
 [7 8]]


In [5]:
print(arr2[1:2,1:2])

[[4]]


In [7]:
print(arr2[0:2,0:2])

[[0 1]
 [3 4]]


In [9]:
# Array Operators.....

import numpy as np
arr1=np.arange(9)
print(arr1)
print()
arr2=arr1.reshape(3,3)
print(arr2)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# Array Oprators.....
# print(arr2)
# print(arr2.shape)
# print(arr2.ndim)
# print(arr2.dtype)
# print(arr2.itemsize)
# print(arr2.size)
# prit(arr2.min())
# print(arr2.max())
# print(arr2.sum())
# print(np.sqrt(arr2))
# print(np.std(arr2))

print(arr2,'\n')
print(arr2.shape,'\n')
print(arr2.ndim,'\n')
print(arr2.itemsize,'\n')
print(arr2.size,'\n')
print(arr2.dtype,'\n')
print(arr2.min(),'\n')
print(arr2.max(),'\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

(3, 3) 

2 

4 

9 

int32 

0 

8 



In [20]:
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
print(np.sqrt(arr2))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [22]:
print(np.std(arr2))

2.581988897471611


In [23]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
print(arr2[1:2])

[[3 4 5]]


In [25]:
print(arr2[1:2].sum())

12


In [27]:
print(arr2[1:3,1:3].sum())

24


In [44]:
# Empty Array

array5=np.empty([3,2],dtype= float)
array5

array([[9.34577196e-307, 9.34598246e-307],
       [1.60218491e-306, 1.69119873e-306],
       [1.24611673e-306, 1.05699581e-307]])

In [42]:
arra2=np.empty([3,2],dtype= int)
arra2

array([[-2035567456,         337],
       [          0,           0],
       [          1,           0]])

In [35]:
array2=np.empty([4,4],dtype= str)
array2

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [46]:
array=np.empty([5,5],dtype= bool)
array

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False,  True,  True, False, False],
       [False, False, False, False, False]])

In [47]:
arr1=np.array([10,20,30],dtype=float)
arr1

array([10., 20., 30.])

In [51]:
arra1=np.array([1,2,3],dtype=float)
arra1

array([1., 2., 3.])

In [53]:
arra2=np.array([1,2,3],dtype=np.float16)
arra2

array([1., 2., 3.], dtype=float16)

In [54]:
arra2=np.array([1,2,3],dtype=bool)
arra2

array([ True,  True,  True])

In [61]:
arra2=np.array([1,2,3,0,4,0,9])
arra2

array([1, 2, 3, 0, 4, 0, 9])

In [62]:
arra2.astype(bool)

array([ True,  True,  True, False,  True, False,  True])

In [63]:
array2=np.array([10,20,30])
array2

array([10, 20, 30])

In [64]:
array2.astype(str)

array(['10', '20', '30'], dtype='<U11')

In [65]:
array2.astype(bool)

array([ True,  True,  True])

In [67]:
array2.astype(float)

array([10., 20., 30.])

In [68]:
# Numpy Sort

arra1=np.array([8,7,5,3,2,1,9])
arra2=np.sort(arra1)
arra2

array([1, 2, 3, 5, 7, 8, 9])

In [73]:
array1=np.array(["banana","chery","apple"])
print(array1)
array2=np.sort(array1)
print("sorting array:")
print(array2)

['banana' 'chery' 'apple']
sorting array:
['apple' 'banana' 'chery']


In [76]:
array1=np.array([[2,1,3],[9,8,7]])
print(array1)
array2=np.sort(array1)
array2

[[2 1 3]
 [9 8 7]]


array([[1, 2, 3],
       [7, 8, 9]])

In [79]:
array1=np.array([[20,10,30],[70,90,80]])
print(array1)
pajju=np.sort(array1,axis=0)
print()
print(pajju)

[[20 10 30]
 [70 90 80]]

[[20 10 30]
 [70 90 80]]


In [81]:
print(np.sort(array1,axis=1))

[[10 20 30]
 [70 80 90]]


In [82]:
# Numpy delete
# The numpy.delete() function return a new array with the deletion of sub-arrays along withb mentioned axis

import numpy as np
arr1=np.arange(10,19)
print(arr1)

[10 11 12 13 14 15 16 17 18]


In [84]:
arr2=arr1.reshape(3,3)
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [85]:
arr3=np.delete(arr2,1,1)
arr3

array([[10, 12],
       [13, 15],
       [16, 18]])

In [86]:
arr3=np.delete(arr2,1,0)
arr3

array([[10, 11, 12],
       [16, 17, 18]])

In [87]:
arr1=np.arange(10,22)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [88]:
arr2=arr1.reshape(4,3)
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [89]:
a=np.delete(arr2,2,0)
a

array([[10, 11, 12],
       [13, 14, 15],
       [19, 20, 21]])

In [91]:
a=np.delete(arr2,0,1)
a

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21]])

In [92]:
arr1=np.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [93]:
arr2=np.delete(arr1,2)
arr2

array([10, 20, 40])

In [94]:
np.delete(arr1,[2,3])

array([10, 20])

In [96]:
arr2=np.arange(10,22)
print(arr2)
arr3=arr2.reshape(3,4)
arr3

[10 11 12 13 14 15 16 17 18 19 20 21]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [97]:
arr4=np.delete(arr3,1,0)
arr4

array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [98]:
arr4=np.delete(arr3,2,1)
arr4

array([[10, 11, 13],
       [14, 15, 17],
       [18, 19, 21]])

In [99]:
arr3

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [101]:
arr4=np.delete(arr3,2,0)
arr4

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [103]:
arr4=np.delete(arr3,3,1)
arr4

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])